### ISSUE TITLE
Error in package-requires line

### ISSUE THREAD

**Issue by jian-lin** [emacsfodder/emacs-theme-sakura#1]
This makes MELPA fail to parse dependencies: https://melpa.org/#/sakura-theme

ref: https://github.com/NixOS/nixpkgs/issues/335442

**Comment by jasonm23** [comment]
```elisp
;;; Package-Requires
```

Should be

```elisp
;; Package-Requires
```

**Comment by jian-lin** [comment]
should be fixed by https://github.com/emacsfodder/emacs-theme-sakura/commit/22d36d0a9b05e4e24ec701c585145b032e42bc7a

**Comment by jasonm23** [comment]
> should be fixed by [22d36d0](https://github.com/emacsfodder/emacs-theme-sakura/commit/22d36d0a9b05e4e24ec701c585145b032e42bc7a)

should be
